### ISSUE TITLE
Property Widget: action button icons can get outside content group area depending on widget width

### ISSUE THREAD

**Issue by AnDuong249** [imodeljs/viewer-components-react#511]
**Repro Steps:**
1. Select any element in the view.
2. In properties widget, add favorite property and share it.
3. Start reducing panel width where properties widget is housed.
4. **Notice** that at certain point, share icon starts to clip content group border and eventually gets outside the borders. It would be ideal, to treat share icon as a content within the group and keep it within the borders.
![image](https://github.com/iTwin/viewer-components-react/assets/116378951/e9d4460d-499e-4310-bdfd-21902deceff3)

**Note**: As you reduce the width further to min-width, the icon position did get corrected however.
![image](https://github.com/iTwin/viewer-components-react/assets/116378951/e642022e-1d4a-4d45-a2a7-6ca848e57c28)

Version used: 
@itwin/property-grid-react: 0.9.0

Here's our work item:
https://dev.azure.com/bentleycs/beconnect/_boards/board/t/iModel%20Viewer%20Framework%20Service/Backlog%20items/?workitem=1198433

**Comment by saskliutas** [comment]
Can you try out `@itwin/property-grid-react: 0.10.0`? It should work fine in that version.

**Comment by AnDuong249** [comment]
Seems like that fixes the problem. Thank you!
