### ISSUE TITLE
Tree Widget: progress indicator is too big in "enlarged" layout

### ISSUE THREAD

**Issue by yoannna** [imodeljs/viewer-components-react#698]
Progress indicator when tree density is set to "enlarged":
![image](https://github.com/iTwin/viewer-components-react/assets/22612644/29de028c-e192-4d3f-a98d-e3b7045e5ff8)

The progress indicator should stay the same size as in the default layout.

**Comment by ViliusBa** [comment]
Hello, thanks for submitting the issue. 

I am having a hard time reproducing this issue, could you tell me what versions of `@itwin\itwinui-react` and `@itwin\tree-widget` are you using?

**Comment by JoanaSmit** [comment]
@ViliusBa
We're using `@itwin\itwinui-react` 2.11.2 and `@itwin/tree-widget-react` 1.2.0
The issue appeared after touch-friendly layout enhancement: https://github.com/iTwin/viewer-components-react/issues/565

@aruniverse
We're using your SDKs in the Field app
